name: Bump version on push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Configure Git identity
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Bump version for root package.json
      run: |
        npm version patch --no-git-tag-version
        git add package.json package-lock.json
        git commit -m "Bump version [skip ci]"
        
    - name: Bump version for app/package.json
      run: |
        cd app
        npm version patch --no-git-tag-version
        git add package.json package-lock.json
        git commit -m "Bump version in app [skip ci]"
        cd ..

    - name: Push changes
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
        git push
      
