name: Bump version on push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Bump version for root
      uses: phips28/gh-action-bump-version@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        PACKAGEJSON_DIR: './'

    - name: Bump version for app
      uses: phips28/gh-action-bump-version@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        PACKAGEJSON_DIR: './app'
