name: Run Prisma Migrations

on:
  push:
    branches:
      - main

jobs:
  run_migrations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Check commit message for migration trigger
        run: |
          echo "MIGRATION_NEEDED=$(git log -1 --pretty=%B | grep -q 'DB-MIGRATE-MANIFEST' && echo 'true' || echo 'false')" >> $GITHUB_ENV

      - name: Install Dependencies with Bun
        run: |
          bun install

      - name: Pull latest changes
        run: |
          git config pull.rebase false
          git pull

      - name: Run DB Migrations with Bun
        run: bun prisma migrate deploy
        if: env.MIGRATION_NEEDED == 'false'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run DB Migrations with Bun
        run: bun prisma migrate dev --name ${{ github.run_id }}
        if: env.MIGRATION_NEEDED == 'true'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Enable Realtime on All Tables
        run: psql $DATABASE_URL -f enable_realtime.sql
        working-directory: manifest
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Commit Migrations
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add prisma/migrations/*.sql
          # Only commit and push if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automate migration"
            git push
          fi
