name: Run Prisma Migrations

on:
  push:
    branches:
      - main

jobs:
  run_migrations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Fetch all history for comparison
        run: git fetch --depth=2

      - name: Print diff
        run: git diff --name-only HEAD^ HEAD
  
      - name: Check if file is modified
        id: check_file
        run: |
          # Check if the file has been modified
          if git diff --name-only HEAD^ HEAD | grep -q 'prisma/schema.prisma'; then
            echo "MIGRATION_NEEDED=true" >> $GITHUB_ENV
          else
            echo "MIGRATION_NEEDED=false" >> $GITHUB_ENV
          fi

      - name: Install Dependencies with Bun
        run: |
          bun install

      - name: Run DB Migrations with Bun
        run: bun prisma db push --accept-data-loss
        if: env.MIGRATION_NEEDED == 'true'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Enable Realtime on All Tables
        run: psql $DATABASE_URL -f enable_realtime.sql
        working-directory: manifest
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Commit Migrations
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull
          git add prisma/migrations/*.sql
          # Only commit and push if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automate migration"
            git push
          fi
