name: Run Prisma Migrations

on:
  push:
    branches:
      - main

jobs:
  run_migrations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Check if schema.prisma is modified or first commit
        id: check_file
        run: |
          # Check if this is the first commit or if the Prisma schema file has been modified
          if [ $(git rev-list --count HEAD) -eq 1 ] || git diff --name-only HEAD^ HEAD | grep -q 'prisma/schema.prisma'; then
            echo "MIGRATION_NEEDED=true" >> $GITHUB_ENV
          else
            echo "MIGRATION_NEEDED=false" >> $GITHUB_ENV
          fi

      - name: Install Dependencies with Bun
        run: |
          bun install

      - name: Apply Pending Migrations
        uses: nick-fields/retry@v3
        if: env.MIGRATION_NEEDED == 'true'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          timeout_minutes: 5
          max_attempts: 10
          retry_on: error
          command: bun prisma migrate deploy
          warning_on_retry: true
          retry_wait_seconds: 10

      - name: Run Prisma Migrations
        uses: nick-fields/retry@v3
        if: env.MIGRATION_NEEDED == 'true'
        id: db_migration
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        with:
          timeout_minutes: 5
          max_attempts: 10
          retry_on: error
          command: bun prisma db push --accept-data-loss
          warning_on_retry: true
          retry_wait_seconds: 30

      - name: Enable Realtime on All Tables
        run: psql $DATABASE_URL -f enable_realtime.sql
        working-directory: .github/scripts/
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Commit Migrations
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull
          git add prisma/migrations/*.sql
          # Only commit and push if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automate migration"
            git push
          fi
