name: Run Prisma Migrations

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  run_migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm ci # or use `npm install` if you don't have a lock file

      - name: Run DB Migrations
        run: npx prisma migrate dev
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
