name: Run Prisma Migrations

on:
  push:
    branches:
      - main # or your default branch name

jobs:
  run_migrations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies with Bun
        run: |
          bun install

      - name: Run DB Migrations with Bun
        run: bun prisma migrate dev
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
