name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_TOKEN }}
          heroku_app_name: manifest-${{ github.event.repository.name }}
          heroku_email: loama18@gmail.com
          team: manifest-hq
          justlogin: true
      - run: heroku git:remote -a manifest-${{ github.event.repository.name }}
      - run: git push heroku main
