name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Heroku
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku plugins:install heroku-builds

      - name: Log in to Heroku
        run: heroku login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}

      - name: Deploy to Heroku
        run: |
          heroku git:remote -a manifest-${{ github.event.repository.name }}
          git push heroku main
          heroku builds:create --app manifest-${{ github.event.repository.name }}
