name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # This action will handle the deployment to Heroku
      with:
        heroku_api_key: ${{ secrets.HEROKU_TOKEN }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: loama18@gmail.com
