name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git remote rm heroku && git remote add heroku https://git.heroku.com/manifest-${{ github.event.repository.name }}.git
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: manifest-${{ github.event.repository.name }}
          heroku_email: loama18@gmail.com
          team: manifest-hq
