name: Release app version

on:
  push:
    branches:
      - main

jobs:
  run_migrations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies with Bun
        run: |
          bun install

      - name: Release
        run: bun release.js
