name: Release app version

on:
  push:
    branches:
      - main

jobs:
  release_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies with Bun
        run: bun install

      - name: Release
        run: bun release-app.js
