name: Sync Files to Manifest
on:
  push:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  sync-to-manifest-db:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          mv package.json package.json_backup
          bun i cheerio@^1.0.0-rc.12 fs@^0.0.1-security path@^0.12.7 @supabase/supabase-js axios
          mv package.json_backup package.json

      - name: Sync Files
        env:
          GITHUB_REPO_NAME: ${{ github.repository }}
          SUPABASE_URL: ${{ secrets.MANIFEST_SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.MANIFEST_SUPABASE_PUBLISHABLE_KEY }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: node .github/scripts/sync-files-to-supabase.js $BRANCH_NAME

      - name: Release
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: node .github/scripts/pre-release.js $BRANCH_NAME
