name: Sync to Firestore

on:
  push:
    branches:
      - '*' # all branches

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Save Release Info to Firestore
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > serviceAccountKey.json
        npm install firebase-admin
        node .github/scripts/sync_to_firestore.js
      env:
        FIREBASE_PROJECT_ID: manifest-hq
