name: Sync Files to Manifest
on:
  push:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  sync-to-supabase:
    if: "!contains(github.event.head_commit.message, 'IGNORE_ACTIONS')"
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Check commit message
        run: |
          echo "SKIP_ACTION=$(git log -1 --pretty=%B | grep -q 'DONT-ADD-TAGS' && echo 'true' || echo 'false')" >> $GITHUB_ENV

      - name: Install dependencies
        if: env.SKIP_ACTION == 'false'
        run: |
          mv package.json package.json_backup
          bun i cheerio@^1.0.0-rc.12 fs@^0.0.1-security path@^0.12.7 @supabase/supabase-js
          mv package.json_backup package.json

      # - name: Add tag-id to Vue files
      #  if: env.SKIP_ACTION == 'false'
      #  run: node manifest/add-tag-id-to-vue-files.js

      #- name: Commit changes
      #  if: env.SKIP_ACTION == 'false'
      #  run: |
      #    git config --local user.email "action@github.com"
      #    git config --local user.name "GitHub Action"
      #    git add -A
      #    git commit -m "Automatically add tag-id to Vue files" || echo "No changes to commit"
      #    git push

      - name: Sync Files
        if: env.SKIP_ACTION == 'false'
        env:
          GITHUB_REPO_NAME: ${{ github.repository }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: node .github/scripts/sync-files-to-supabase.js $BRANCH_NAME

      - name: Release
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: node .github/scripts/pre-release.js $BRANCH_NAME
